GET https://2uglo6gd70.execute-api.ap-southeast-2.amazonaws.com/prod/properties
###

GET https://2uglo6gd70.execute-api.ap-southeast-2.amazonaws.com/prod/properties?id=4b305fd7-a434-47de-84dd-ea5fbe9c8341
###

DELETE https://2uglo6gd70.execute-api.ap-southeast-2.amazonaws.com/prod/properties?id=811d67b2-6871-436b-8d6e-323c81642238
###

POST https://2uglo6gd70.execute-api.ap-southeast-2.amazonaws.com/prod/properties
Content-Type:application/json

{
    "address": "zzz",
    "description": "my description testing"
}
###

PUT https://2uglo6gd70.execute-api.ap-southeast-2.amazonaws.com/prod/properties?id=75090c83-8d1a-41b2-89b1-298f7462676c
Content-Type:application/json

{
   "description": "holly st yeer"
}
###

